4.2.2
实现CNN

In [1]:
import torch
from torch.nn import Conv1d #表示一维卷积，适用于自然语言
#Cov2d和Cov3d表示二维和三维卷积

In [2]:
conv1=Conv1d(5,2,4) #一维卷积，输入通道5，输出通道2，卷积核宽度4
conv2=Conv1d(5,2,3) #一维卷积，输入通道5，输出通道2，卷积核宽度3
inputs=torch.rand(2,5,6) #输入批次2即两个序列，每个序列输入维度5，长度为6

In [8]:
inputs

tensor([[[0.0230, 0.8468, 0.2994, 0.3425, 0.8425, 0.7550],
         [0.9124, 0.5812, 0.5492, 0.8224, 0.8393, 0.1501],
         [0.6326, 0.6055, 0.3070, 0.6559, 0.3498, 0.9794],
         [0.5572, 0.4400, 0.1227, 0.1021, 0.8734, 0.2615],
         [0.1450, 0.6261, 0.0460, 0.2124, 0.6859, 0.8547]],

        [[0.0374, 0.3931, 0.5073, 0.0149, 0.1785, 0.3768],
         [0.3318, 0.7702, 0.6960, 0.8896, 0.0904, 0.0399],
         [0.9909, 0.8062, 0.3611, 0.5985, 0.2865, 0.5712],
         [0.1049, 0.0157, 0.0320, 0.6258, 0.3582, 0.2579],
         [0.4836, 0.6940, 0.1712, 0.8985, 0.4501, 0.2094]]])

In [9]:
outputs1=conv1(inputs)
outputs2=conv2(inputs)

In [4]:
print(outputs1)

tensor([[[-0.3946, -0.4624, -0.4250],
         [-0.5367, -0.5206, -0.5997]],

        [[-0.3284, -0.6317, -0.5092],
         [-0.6662, -0.6216, -0.4186]]], grad_fn=<ConvolutionBackward0>)


In [5]:
print(outputs2)

tensor([[[-0.0520,  0.0743,  0.3065, -0.1350],
         [ 0.0278, -0.3540, -0.2838, -0.5484]],

        [[ 0.0988,  0.0384, -0.0265,  0.0216],
         [-0.5463, -0.4574, -0.6286, -0.2142]]],
       grad_fn=<ConvolutionBackward0>)


In [10]:
from torch.nn import MaxPool1d #一维最大池化，由结果看出最大池化即保留输入中最大的一个数据，即最重要的特征
pool1=MaxPool1d(3) #池化范围，输入的维度3，输出维度1
pool2=MaxPool1d(4)

In [11]:
outpool1=pool1(outputs1) #定义池化对象
outpool2=pool2(outputs2)

In [12]:
print(outpool1)

tensor([[[-0.3946],
         [-0.5206]],

        [[-0.3284],
         [-0.4186]]], grad_fn=<SqueezeBackward1>)


In [13]:
print(outpool2)

tensor([[[ 0.3065],
         [ 0.0278]],

        [[ 0.0988],
         [-0.2142]]], grad_fn=<SqueezeBackward1>)


In [14]:
import torch.nn.functional as F #使用池化函数，不用定义池化对象
foutpool1=pool1(outputs1)
foutpool2=pool2(outputs2)

In [15]:
print(foutpool1)
print(foutpool2)

tensor([[[-0.3946],
         [-0.5206]],

        [[-0.3284],
         [-0.4186]]], grad_fn=<SqueezeBackward1>)
tensor([[[ 0.3065],
         [ 0.0278]],

        [[ 0.0988],
         [-0.2142]]], grad_fn=<SqueezeBackward1>)


In [20]:
outpool1_squeezq=outpool1.squeeze(dim=2) 
outpool2_squeezq=outpool2.squeeze(dim=2)

[squeeze函数具体用法](https://blog.csdn.net/qq_40305043/article/details/107767652)

In [21]:
outpool1_squeezq

tensor([[-0.3946, -0.5206],
        [-0.3284, -0.4186]], grad_fn=<SqueezeBackward1>)

In [22]:
outpool2_squeezq

tensor([[ 0.3065,  0.0278],
        [ 0.0988, -0.2142]], grad_fn=<SqueezeBackward1>)

In [23]:
outpool=torch.cat([outpool1_squeezq,outpool2_squeezq],dim=1)
outpool

tensor([[-0.3946, -0.5206,  0.3065,  0.0278],
        [-0.3284, -0.4186,  0.0988, -0.2142]], grad_fn=<CatBackward0>)

In [25]:
from torch.nn import Linear
linear=Linear(4,2)
outputs_linear=linear(outpool)
print(outputs_linear)

tensor([[-0.6369, -0.1247],
        [-0.4835, -0.1214]], grad_fn=<AddmmBackward0>)


In [26]:
linear=Linear(4,1)
reoutputs_linear=linear(outpool)
print(reoutputs_linear)

tensor([[0.1785],
        [0.2503]], grad_fn=<AddmmBackward0>)
