4.3.3 实现RNN和LSTM

RNN

In [1]:
import torch
from torch.nn import RNN
rnn=RNN(input_size=4,hidden_size=5,batch_first=True) #输入大小4，隐含层大小5
# bidirectional=True则初始化双向，num_layers则是stack层数
inputs=torch.rand(2,3,4) #2批，长度3，输入大小4
inputs

tensor([[[0.9366, 0.8945, 0.9704, 0.0050],
         [0.7525, 0.5104, 0.1873, 0.6400],
         [0.6770, 0.8196, 0.8537, 0.6706]],

        [[0.0231, 0.7028, 0.2934, 0.8803],
         [0.4096, 0.9832, 0.0287, 0.2672],
         [0.0784, 0.7825, 0.7534, 0.9239]]])

In [2]:
outputs,hn=rnn(inputs) #分别为输出序列的隐藏层和最后一个时刻的隐含层

In [3]:
outputs

tensor([[[-0.3566,  0.5323, -0.3385, -0.7976, -0.6363],
         [-0.3614,  0.2002, -0.5836, -0.5627, -0.8362],
         [-0.5973,  0.0879, -0.7541, -0.6465, -0.8398]],

        [[-0.1021, -0.0315, -0.2058, -0.3538, -0.7843],
         [-0.1939, -0.0235, -0.3721, -0.4428, -0.7386],
         [-0.4825, -0.2174, -0.6149, -0.4230, -0.8527]]],
       grad_fn=<TransposeBackward1>)

In [4]:
hn #可以看出和outputs的最后一列相同

tensor([[[-0.5973,  0.0879, -0.7541, -0.6465, -0.8398],
         [-0.4825, -0.2174, -0.6149, -0.4230, -0.8527]]],
       grad_fn=<StackBackward0>)

In [5]:
outputs.shape,hn.shape

(torch.Size([2, 3, 5]), torch.Size([1, 2, 5]))

LSTM

In [6]:
from torch.nn import LSTM
lstm=LSTM(input_size=4,hidden_size=5,batch_first=True) #和RNN一样的初始化

In [7]:
inputs=torch.rand(2,3,4)
inputs

tensor([[[0.4820, 0.4873, 0.1402, 0.9324],
         [0.3015, 0.0758, 0.6001, 0.5374],
         [0.8970, 0.4452, 0.1608, 0.9968]],

        [[0.9296, 0.4101, 0.0971, 0.3363],
         [0.3109, 0.2829, 0.5303, 0.0740],
         [0.1923, 0.4175, 0.1027, 0.7582]]])

In [8]:
outputs,(hn,cn)=lstm(inputs) #cn是最后一个时刻的记忆细胞
outputs

tensor([[[ 0.0787, -0.2196,  0.1387, -0.0410, -0.0141],
         [ 0.0817, -0.2679,  0.1216, -0.0111, -0.0161],
         [ 0.1433, -0.2756,  0.1505, -0.0220, -0.0069]],

        [[ 0.0708, -0.2007,  0.0925, -0.0261,  0.0157],
         [ 0.0881, -0.2450,  0.0953,  0.0057, -0.0011],
         [ 0.1298, -0.2915,  0.1719, -0.0189, -0.0424]]],
       grad_fn=<TransposeBackward0>)

In [9]:
hn

tensor([[[ 0.1433, -0.2756,  0.1505, -0.0220, -0.0069],
         [ 0.1298, -0.2915,  0.1719, -0.0189, -0.0424]]],
       grad_fn=<StackBackward0>)

In [10]:
cn

tensor([[[ 0.3455, -0.5903,  0.3513, -0.0590, -0.0128],
         [ 0.2717, -0.5986,  0.4071, -0.0417, -0.0783]]],
       grad_fn=<StackBackward0>)

In [11]:
outputs.shape,hn.shape,cn.shape

(torch.Size([2, 3, 5]), torch.Size([1, 2, 5]), torch.Size([1, 2, 5]))